### ISSUE TITLE
ここにアイデアとバグを貯める

### ISSUE THREAD

**Issue by eastwd** [m-masataka/oppai_iga#3]

**Comment by m-masataka** [comment]
ToDoを書くよ！
・データベースの使用。
　-OBJファイルをデータベースで管理
・IGA　<- 一番重要
　-今のおっぱいのパラメータは4つしかないけど、パラメータの増減に対応できるコードが良いな
・IGAで使うWebUI
  -卒論・修論のやつみたいなの期待
・構築自動化
- ansible 良いね！

・もっとリアルなおっぱいの作成
　-目下検討中 いまのところblenderを使用。　＜－良い方法あったら教えて

**Comment by eastwd** [comment]
ナイス！

3DモデルのファイルをDBに入れようとすると、
 1 DBに入れるのはユーザが指定したパラメータ(models.pyに書く)
 2 DBからパラメータをもらって、OBJファイルの形式でレスポンスを返すページを作る(views.pyに書く)
 3 2にアクセスして、3Dモデルをjavascriptで出力するページを作る
みたいな感じになりそう

とりあえずplaybook書き終わったら、データベースに保存するように変更してく！

**Comment by eastwd** [comment]
ansible書き終わった

**Comment by eastwd** [comment]
ぼんのうサーバの作成に最近ちょっと忙しくなってた

自動構築はdockerに書き直した方がいい？

**Comment by m-masataka** [comment]
長らく手付かずになっててごめんm(. .)m
dockerやりたいね！楽になるし、
あれやね、IGAとmysqlと連携する部分つくってみるよ

**Comment by eastwd** [comment]
OK!

**Comment by m-masataka** [comment]
というかすっかり見落としてたけど、
ぼんのうサーバ作ってるの？！

**Comment by eastwd** [comment]
GO言語で書き直したぜb(to ぼんのうサーバ)

**Comment by eastwd** [comment]
dockerfile書き終わった

**Comment by eastwd** [comment]
気になったんだけど、今ってpythonのバージョン何で書いてる??
