### ISSUE TITLE
かっこいい名前をつける

### ISSUE THREAD

**Issue by eastwd** [m-masataka/oppai_iga#6]
リポジトリ名がちょっと気になるので、OSSっぽいかっこいい名前に変えたいw

**Comment by m-masataka** [comment]
俺も変えたいw
これ他人に見られるのが地味にきになるね（。）（。）

**Comment by eastwd** [comment]
やっぱ水越もそうだったかw！

**Comment by m-masataka** [comment]
案１　OPIGA 
案２   WebModellingIGA
何か良い案がアルカナ？

**Comment by eastwd** [comment]
個人的には別の言語から取ってきてもいいかなと思ってる

"美しい円"でgoogle翻訳にかけた結果
- hermosa círculo　スペイン語
- mooie cirkel　オランダ語
- cerc frumos　ルーマニア語
美人が多そうな国から選定してみた！

とはいえ適当に言ってるだけだから、水越が自由に決めていいよ！

**Comment by m-masataka** [comment]
遅くなりました。
スペイン語を採用します！
